[package]
name = "gygesUI"
version = "1.0.0"
edition = "2021"

[profile.release]
opt-level = 3
lto = true
panic = "unwind"
codegen-units = 1
debug = false

[dependencies]
macroquad = "0.4.4"
winapi = "0.3.9"
